dynamixel_mx:
  port: "/dev/ttyACM0"
  baudrate_board: 115200

  origin_pose: 1834 # 0°

  #            -25°,  45°
  scan_poses: [2130, 1327]

  init_pose: 2130 #-25°
  final_pose: 1327 #45°

  step_org: 20
  step_scan: 3
  delta_error: 5
  resolution: 11.175

map_hokuyo:
  origins:
    world2motor:
      xyz: [0, 0, 1.25]

    motor2lidar:
      xyz: [0, 0, 0.05]

  coordinate:
    xyz: [-12.127, 0.4, -0.6099]
    rpy: [0, 0, 180]

    # Roll = X
    # Pitch = Y
    # Yaw = Z
